[project]
name = "datura-test"
description = "Coding test"
requires-python = "==3.12.*"
authors = [
    {name = "Sergio Herrera", email = "sergioherreravillamil@gmail.com"},
]
readme = "README.md"
dependencies = [
]
version = "0.0.1"
